config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  get '/auth/:provider/callback', to: 'users#create'

  get 'sign-out', to: 'users#sign_out', as: :sign_out

  get 'github-api', to: 'users#github_api'
  get 'lang-chart', to: 'users#language_chart'
  get 'activity', to: 'users#activity'
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def create
    oath_attrs = request.env['omniauth.auth']
    @user = User.find_or_initialize_by(uid: oath_attrs.uid)
    @user.username   = oath_attrs.info.nickname
    @user.email      = oath_attrs.info.email
    @user.avatar_url = oath_attrs.info.image
    @user.token      = oath_attrs.credentials.token
    @user.save
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def sign_out
    session.delete(:user_id)
    redirect_to root_path
  end

  def github_api
    github_user = client.user
    render json: [ location: github_user.location,
                   following: github_user.following,
                   followers: github_user.followers,
                   repos: github_user.public_repos,
                   gists: github_user.public_gists,
                ]
  end

  def language_chart
    hash = Hash.new(0)
    client.repositories.each do |repo|
      if repo.language.nil?
        hash["n/a"] += 1
      else
        hash[repo.language] += 1
      end
    end

    languages = hash.map do |k,v|
      { language: k, repos: v }
    end

    render json: languages
  end

  def activity
    act = client.user_events(current_user.username, per_page: 100)
    hash = Hash.new(0)
    act.each do |repo|
      repo.type.slice!("Event")
      if repo.type.scan(/[A-Z][a-z]+/).count > 1
        repo.type = repo.type.scan(/[A-Z][a-z]+/).join(" ")
      elsif repo.type == "Member"
        repo.type = "Add Collaborator"
      end
      hash[repo.type] += 1
    end

    activity = hash.map do |k,v|
      { activity: k, number: v }
    end

    render json: activity
  end

  def client
    Octokit::Client.new(:access_token => current_user.token)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VisualizeGithub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <%= csrf_meta_tags %>
</head>
<body class="color">

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<% if current_user %>
  <div class="hi">
    <nav>
      <%= link_to "Sign Out", sign_out_path, class: "btn" %>
      <%= link_to "My Github Page", "https://github.com/#{current_user.username}", class: "github-link", target: "blank", class: "btn" %>
    </nav>
    <h1>Hello <%= current_user.username.capitalize %>! It's nice to see you!</h1>
    <%= image_tag "#{current_user.avatar_url}", class: "logo" %>
    <div class="info">
      <div class="l">Location: <span class="location"></span></div>
      <div>Following: <span class="following"></span></div>
      <div>Followers: <span class="followers"></span></div>
      <div># of repos: <span class="repos"></span></div>
      <div># of gists: <span class="gists"></span></div>
    </div>
    <div class="divider"></div>
    <div id="chart-container-activity"></div>
    <div id="chart-container"></div>
  </div>
<% else %>
  <header>
    <%= link_to "Sign in with github", "/auth/github", class: "btn" %>
  </header>
<% end %>